# Generated by Django 3.1.5 on 2021-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='games',
        ),
        migrations.AddField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_system',
            field=models.CharField(choices=[('XBOX1', 'XBOX1'), ('PS4', 'PS4'), ('PS3', 'PS3'), ('SWITCH', 'SWITCH'), ('PC', 'PC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
